version: '3.8'

services:

   demo-be:
      build:
        context: .
      working_dir: /src
      volumes:
         - .:/src
      ports:
         - 127.0.0.1:5002:5002

   database:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: postgres
